repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files

  -   repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
        -   id: black
            exclude: ^dist/

  -   repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
        -   id: isort

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
        -   id: mypy
            files: ^(mypackage/|tests/)
            additional_dependencies:
                - "pydantic>=1.10.4"
            name: Validate types with MyPy

  -   repo: https://github.com/PyCQA/flake8
      rev: 4.0.1  # The git tag for the version you want to use
      hooks:
        -   id: flake8
            args: [--config=.flake8]
