name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version-file: .python-version

    - name: Install dependencies
      run: python -m pip install --upgrade build twine

    - name: Build a binary wheel and a source tarball
      run: python -m build

    - name: Publish to PyPi
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
