name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version build twine

    - name: Bump version
      run: bump2version patch --config-file .bumpversion.cfg

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Build a binary wheel and a source tarball
      run: python -m build

    - name: Publish to PyPi
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
